id: firebase-config-exposure

info:
  name: Firebase Configuration File Exposure Detection
  author: geeknik
  severity: medium
  description: |
    Detects the exposure of Firebase configuration files that contain sensitive credentials such as API keys, authentication domains, database URLs, and storage buckets.
    Exposing this configuration file can allow attackers to abuse the Firebase services linked to the app.
  reference:
    - https://github.com/firebase/firebaseui-web/blob/master/demo/public/sample-config.js
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  tags:
    - firebase
    - exposure
    - config

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{BaseURL}}/public/config.js"
      - "{{BaseURL}}/config.js"
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "apiKey:"
          - "authDomain:"
          - "databaseURL:"
          - "storageBucket:"
        condition: and
      - type: status
        status:
          - 200
